### ISSUE TITLE
Add version to the UI

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/sckan-composer#158]

**Comment by ddelpiano** [comment]
add the version also to the svgs downloaded from the UI (also to the exports?)

**Comment by stappan** [comment]
yes. add version to the svgs downloaded from the UI & exports.

**Comment by ddelpiano** [comment]
@stappan these are the acceptance criteria written for this:

**Acceptance criteria:**
- Add the version to a setting file
- In the left sidebar, at the bottom, add the nomenclature “SCKAN Composer version: 3.2.0” where 3.2.0 is taken from the setting
- add the version also to the export csv, as a comment on top of the csv, along the data of when the csv has been generated.

**Comment by stappan** [comment]
Looks good!

SPARC

Sent via the Samsung Galaxy S22+
________________________________
