### ISSUE TITLE
Invalid state applied incorrectly on ingested statements from NeuronDM

### ISSUE THREAD

**Issue by stappan** [MetaCell/sckan-composer#241]
Date observed: 2/22/2024
Reported by: Sue
Current Behavior:
Ingestion from NeuronDM is configured to flag statements that have missing URIs as invalid. However, a statement marked as invalid does in fact have that URI in the anatomical entity list. 

Where you can see the problem: 
https://composer.scicrunch.io/statement/65 
Dev
Production
Staging

nucleus of the solitary tract 

![image](https://github.com/MetaCell/sckan-composer/assets/106172226/fdf2a150-715e-4001-bc3e-b6ebddf193d6)
![image](https://github.com/MetaCell/sckan-composer/assets/106172226/b6bbdf5b-aa93-45cf-8805-726e0dace860)
![image](https://github.com/MetaCell/sckan-composer/assets/106172226/9299ddbc-717f-4b5f-9eb9-9a1cd5f74a58)

**Comment by stappan** [comment]
![image](https://github.com/MetaCell/sckan-composer/assets/106172226/d9646704-0798-42cf-b9cc-b4b8dce97dd8)

**Comment by ddelpiano** [comment]
@stappan https://github.com/MetaCell/sckan-composer/pull/354 has an explanation of the issue found and fixed

**Comment by stappan** [comment]
addressed in Sprint 21
