### ISSUE TITLE
Modify neurondm ingestion to populate the layer table and store intersections layer+region

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/sckan-composer#243]
When performing the neurondm ingestion we will need to ensure that the following is performed:

- when encountering a layer in the partial order tuple, check if the layer already exists in the layer table, if not check if this exists in the AE table and if yes copy this to the layer table (attention, we are keeping the layer in the AE table, we are just copying it in the layer table).
- If the layer does not exists in the layer table and also in the AE table, then raise an error and set the KS invalid (brief explanation why, the partial order only provides us with the layer URI, if this is missing in the AE table we don't know what label this layer should have, this will required manual curation from the admin to add the layer manually in the system, add the intersection manually and then curate this KS again).

Acceptance criteria:
- when running the ingestion, if a new layer is found this should be added to the layer table
- when running the ingestion, if a new intersection layer+region is found this should be added to the intersection table
- when visualising the proofing tab of a KS that contains an intersection, this should be visible from the path builder label used

**Comment by stappan** [comment]
As a reminder, layers are not required, so if there are only regions, they should be ingested without error

**Comment by ddelpiano** [comment]
> As a reminder, layers are not required, so if there are only regions, they should be ingested without error

Sure 👍🏽
