### ISSUE TITLE
Modify the rest API to expose the new region+layer information plus backedn changes for the searcheable terms

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/sckan-composer#244]
![scrnli_06_03_2024_21-54-20](https://github.com/MetaCell/sckan-composer/assets/37704177/9460159d-9dc9-4098-869e-b4230f46c7b8)

Acceptance criteria:
- when searching for a term (rdfs label or synonym), the anatomical entity search and eventually intersections containing this should be shown in the results. (screenshot above)
- for the intersections, the name shown should be in the form of " region rdfs label **(layer rdfs label)** "

**Comment by stappan** [comment]
@ddelpiano if "and eventually intersections containg this" is a future task, please let's create a ticket for it, and keep this acceptance criteria specific to the actual work being done for clarity's sake. thanks!

**Comment by ddelpiano** [comment]
@stappan the search will search across anatomical entities and intersections, the only limitation I can see right now is that you won't be able to search for an intersection (e.g. Segment L1 Lamina VII) but you will be able to search for the anatomical entity (either region or layer) and regions and intersections that contains the searched term will be returned as part of the results.

**Comment by stappan** [comment]
that's fine, but that's not my point. I want the second aspect that will not be worked on now, moved to another task. so that when the work is done, and checked, the task can be properly closed without losing the secondary feature.
