### ISSUE TITLE
Admin interface changes for region + layer

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/sckan-composer#247]
Acceptance criteria:
- allow the admins to add a region through the admin interface
- allow the admins to add a layer through the admin interface
- allow the admins to add/edit a synonym for an anatomical entity (region, layer)
- allow the admins to add an intersection region+layer through the admin interface
- allow the admins to pick for origins, vias, destinations either an anatomical entity or an intersection region+layer.

**Comment by stappan** [comment]
@ddelpiano is it possible to configure this to permit adding an AE to both region and layer tables via a checkbox or similar? I'm trying to imagine how this will be performed by the admin.

**Comment by ddelpiano** [comment]
> @ddelpiano is it possible to configure this to permit adding an AE to both region and layer tables via a checkbox or similar? I'm trying to imagine how this will be performed by the admin.

@stappan most likely for this first iteration this will require to be added first to the table AE and then to the layer table separately, I will check if we have time to fit this one in.
