### ISSUE TITLE
Population marked as invalid due to missing destination; present in anatomy tables

### ISSUE THREAD

**Issue by stappan** [MetaCell/sckan-composer#278]
Statement 96 is marked as invalid due to missing destination, however the URIs are present in the anatomy table. 

1. (Neck of bladder/connective tissue) region/layer pair exists in table, and marked as destination. 

2. dome of bladder & connective tissue each exist as URIs, but was region/layer pair not created? 

3. (Fundus of urinary bladder/connective tissue) region/layer pair exists in table, but population is marked as invalid because axiom (predicate??) doesn't exist. 

Not sure what the difference is between the 3?

![image](https://github.com/MetaCell/sckan-composer/assets/106172226/15eb5f9d-61b8-4faa-bf64-ed3a5624ceae)

these are all in the anatomy tables:
http://purl.obolibrary.org/obo/UBERON_0001135
http://purl.obolibrary.org/obo/UBERON_0006082
http://purl.obolibrary.org/obo/UBERON_0002384
http://uri.interlex.org/base/ilx_0738433

**Comment by stappan** [comment]
![image](https://github.com/MetaCell/sckan-composer/assets/106172226/37eeae13-a6f5-4e64-92d0-190c107824a1)
![image](https://github.com/MetaCell/sckan-composer/assets/106172226/37eeae13-a6f5-4e64-92d0-190c107824a1)

**Comment by ddelpiano** [comment]
@stappan I agree with you it's weird, this will require additional time to investigate the problem but I found weird that the layer has not been created since region (fundus of the urinary bladder) and the layer (muscle tissue) are both present. My guess is that one of these 2 could have been added later or otherwise there is a bug in the ingestion we need to fix, either of them will require a further analysis, adding this to the backlog.

**Comment by stappan** [comment]
Are you able to create the region/layer pair for this entity? because i can't.

https://github.com/MetaCell/sckan-composer/assets/106172226/956f5dca-6888-4a4a-94df-4538e7af950e

**Comment by stappan** [comment]
https://github.com/MetaCell/sckan-composer/assets/106172226/872f430d-6dc4-4c8b-8e60-f8442c8a652e

Also, demonstrating using the magnifying glass to search for both entities

**Comment by ddelpiano** [comment]
@D-GopalKrishna when creating a region, it seems that it fails if the anatomical entity using the uri already exists.
