### ISSUE TITLE
Error when attempting to create new region/layer pair

### ISSUE THREAD

**Issue by stappan** [MetaCell/sckan-composer#279]
When trying to create a new region/layer pair, I get an error message.

To reproduce: 
1. paste URI for dome of bladder in Region: http://uri.interlex.org/base/ilx_0738433
2. search using magnifying glass "smooth muscle" in Layer. 
3. select the correct existing entry (smooth muscle tissue http://purl.obolibrary.org/obo/UBERON_0001135) by selecting hyperlinked text
**note field returned value = 14795 **
4. Select save
5. See error. 

![image](https://github.com/MetaCell/sckan-composer/assets/106172226/c7213197-70c5-4685-955f-a67f4b06eb25)

**Comment by stappan** [comment]
Order (layer then region) doesn't matter; neither does adding URIs instead of text 
Also, searching for Dome of Bladder in region doesn't find the entry, but trying to add the entity as a region manually  indicates that it is already existing. 
![image](https://github.com/MetaCell/sckan-composer/assets/106172226/7638a6b9-228a-4a25-9091-5206a0baadda)
[not sure if this is a different issue? or the root cause of the issue]

**Comment by ddelpiano** [comment]
Hi @stappan , 
please find attached  a video that shows how to add a region/layer pair, if you have any question let me know. Thanks :) 

[scrnli_6_7_2024_2-49-48 PM.webm](https://github.com/MetaCell/sckan-composer/assets/37704177/a81333a1-7334-46c0-9b18-b05902833beb)

**Comment by stappan** [comment]
here's an explicit video showing the failure. i don't think this is fixed. 

https://github.com/MetaCell/sckan-composer/assets/106172226/ede4f0aa-0f54-4164-8110-19660925e798
