### ISSUE TITLE
Population Diagram Styling: overdrawing when there's a branch

### ISSUE THREAD

**Issue by stappan** [MetaCell/sckan-composer#283]
All vias are aligned in a single vertical, even when there is branching, making it a) a much longer diagram than necessary, and b) making it seem like the modeling is wrong.

request: separate different branched paths into separate "columns" to make it easier to review.
see screenshot for https://composer.scicrunch.io/statement/24
![image](https://github.com/MetaCell/sckan-composer/assets/106172226/cf80c3fb-1580-4a27-8da1-21ef3c7817f1)

**Comment by stappan** [comment]
This may be happening when the initial (first) destination is an afferent terminal. if the first destination in the list is an axon terminal, it might be behaving properly.

**Comment by ddelpiano** [comment]
@stappan I think this can be closed due to the smart routing implemented in 3.2.0, feel free to reopen it if needed. Thanks!
