### ISSUE TITLE
unpopulated csv file when exporting statements from Composer

### ISSUE THREAD

**Issue by stappan** [MetaCell/sckan-composer#293]
I'm not able to generate an csv with statement data when I export in Composer. I have 2x now to export 34 statements from NPO approved to generate the csv, but no document is created. The second time I select "export" a csv file is created, however, there are no statements, only headers. 

**[Second time I select "export"](https://composer.scicrunch.io/admin/composer/exportbatch/7/change/)** 
![image](https://github.com/user-attachments/assets/a76fe7ea-da64-41ba-b80c-4e47760e31c8)
[export_2024-09-13_19-04-36.csv](https://github.com/user-attachments/files/16998539/export_2024-09-13_19-04-36.csv)
[export_2024-09-13_18-50-26.csv](https://github.com/user-attachments/files/16998540/export_2024-09-13_18-50-26.csv)

**Comment by ddelpiano** [comment]
It seems to be a performance issue in the export module when going over a certain number of KSs to export.

**Comment by ddelpiano** [comment]
This has been fixed in development already
