### ISSUE TITLE
modify neurondm ingestion to filter out apinatomy population

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/sckan-composer#298]
we might want to implement a flexible filter, so that this can be reused in the future to filter out other KSs that are matching a certain criteria given, so that is not just apinatomy populations.

Priority: High

Acceptance criteria:
The requirement is that we need to re-run the neurondm ingestion to get all the new non-apinatomy population in composer.

**Comment by tgbugs** [comment]
https://github.com/MetaCell/sckan-composer/blob/8e1476fdab9a1dd94264e830a5f61ef57cb6902f/backend/composer/services/cs_ingestion/neurondm_script.py#L442-L444 remove those files (comment out those apinat strings and you can probably comment out https://github.com/MetaCell/sckan-composer/blob/8e1476fdab9a1dd94264e830a5f61ef57cb6902f/backend/composer/services/cs_ingestion/neurondm_script.py#L452-L461 too).

**Comment by stappan** [comment]
this was completed in Sprint 21
