### ISSUE TITLE
[Adjustment] change where floating toolbar icon, microscope, brings you to on the interface

### ISSUE THREAD

**Issue by stappan** [MetaCell/sckan-composer#304]
The microscope icon should bring us to the top of the page, so that we can access the state machine without having to scroll.

**Comment by stappan** [comment]
@ddelpiano please provide effort estimate when you can please.

**Comment by ddelpiano** [comment]
@stappan this was squeezed in 3.2.0, it was a few minutes change that I did when I was working on the autofocus for the anatomical entities drop down. Closing.

**Comment by stappan** [comment]
I noticed! this saves me milliseconds on the regular! thanks!
