### ISSUE TITLE
Feature: include text from alerts ingested from NeuronDM as an editable part of the record

### ISSUE THREAD

**Issue by stappan** [MetaCell/sckan-composer#308]
See: https://composer.scicrunch.io/statement/141
right now, alert text is provided in the notes section of the record, but it should be available as editable part of the record that can also be exported along with the full record.

I think this should perhaps be a new field for entry?

**Comment by ddelpiano** [comment]
Acceptance criteria:
- create a new field in the distillation view, called Alert(s)
- when ingesting from neurondm, the alert message should go in as a block of text in the Alert field.
to be continued

**Comment by ddelpiano** [comment]
@stappan could you remind me the priority for this?
Also, is this duplicated/obsolete due to the latest alerts card you opened? Thanks

**Comment by ddelpiano** [comment]
https://github.com/MetaCell/sckan-composer/issues/328

**Comment by stappan** [comment]
@ddelpiano yes, this is OBE now with the new consolidated request for the alerts in #328

**Comment by stappan** [comment]
Ingest existing alert statements into alerts is covered in #391 now.
