### ISSUE TITLE
Alert system 

### ISSUE THREAD

**Issue by stappan** [MetaCell/sckan-composer#328]
Design description
for the UI:

- a new collapsible section called Statement Alerts is added to the Distillation view, below Statement Details
- Each Alert Type is configured in the Admin area of Composer, & a button/chip sized to display the full text of the label is provided.
- chip label is not truncated. it is the full length of the alert name.
- once clicked, the button/chip creates a text box in the Statement Alert section. 
- the chip label changes from the unadded state ("+ Alert name") to added state ("Alert name")
- focus is moved to the text box, so the curator can immediately begin typing.
- text is automatically saved when clicking away from the text box. All alerts of the same type are concatenated within the single text box.
- hyperlinks should be clickable in the text box. [possible?]
- For chips in the added state, clicking them moves focus for the user to that Alert's text box. 

This mimics the operation and feel for adding a Knowledge Statement to a Sentence (e.g., see light grey box for "Add a knowledge statement" [here](https://composer.scicrunch.io/sentence/314)

for the Admin interface:
A new datatable is created, called Alerts

- to add alert, select green Add Alert button; provide name and URI
- when present, each alert is exported with the knowledge statement.

This behaves just like Species data table.
![image](https://github.com/user-attachments/assets/1dc79f55-b42b-43ff-89a0-8afc3c761bb8)

**Comment by stappan** [comment]
@ddelpiano i would assign this a high priority; and would like to know what is needed from your perspective in order to spec this effectively for effort & delivery estimates (e.g., across how many sprints?)  based on the design i have provided above.

**Comment by stappan** [comment]
@ddelpiano this is a feature that if you don't have enough information to assign effort, that we should discuss in today's meeting. thanks!

**Comment by ddelpiano** [comment]
@stappan we are in the range of the 50 hours, this should take 2 sprints and a half (5 weeks) ready to be released,

**Comment by stappan** [comment]
designated to start Sprint 22

**Comment by ddelpiano** [comment]
@stappan we have some questions about the export:
- from what we discussed in the requirements above, you asked to be able through the admin interface to be able to add the alert type and alert type URI, where should these 2 be exported? I can see these 2 going in the columns identifier and relationship (as we do for sex, species, etc).
- should put something in the predicate as well or this can stay empty? or should the field suggested to go in relationship actually being used for the predicate?
- in which column should the alert text being exported?

Thanks

**Comment by ddelpiano** [comment]
https://metacell.slack.com/archives/D049457VDC0/p1732550901151389?thread_ts=1732116826.695529&cid=D049457VDC0

confirmed by Sue on slack that this should be handled as we do for sex and species.

**Comment by ddelpiano** [comment]
@stappan Still missing requirements about where the alert text should be exported and what to do with the predicate column. Thanks

**Comment by stappan** [comment]
yup @ddelpiano awaiting confirmation from @tgbugs and Fahim.

**Comment by stappan** [comment]
@ddelpiano here are the specifications: we need to be able to specify 3 fields in the admin interface: 
Name: 
Predicate: 
Predicate URI:

For example:
Name: Note
Predicate: alertNote
Predicate URI: http://uri.interlex.org/tgbugs/uris/readable/alertNote
Text that is provided is exported to a column called "Object Text"

Is this the remaining information you needed?

**Comment by ddelpiano** [comment]
Uploading Condivisione schermo - 2024-11-28 15_02_18.mp4…

Latest design with the changes requested! @stappan

**Comment by ddelpiano** [comment]
https://github.com/user-attachments/assets/5b3154c9-5397-46f8-a4ac-40a24e8dab3d

@stappan attached here the latest mockups with the changes requested. Thanks!

**Comment by stappan** [comment]
@ddelpiano testing the Alert system - it does not get the prompt to assign the statement to yourself, and that the statement is in read-only mode. I was able to select an alert & type in the field, but it didn't save.

If you adjust anything in Statement Details, it will signal that prompt, and once it's assigned to yourself, the alert free text are able to saved.

**Comment by ddelpiano** [comment]
Released with 3.2.0

**Comment by stappan** [comment]
@ddelpiano #308 says it is closed because it's request is incorporated into this now closed #328 request. However, you mention in slack that the ingest after release 3.2.0 doesn't include alerts into the record? I'm confused. Can you please investigate/clarify for me?

**Comment by stappan** [comment]
Ingest existing alert statements into alerts is covered in #391 now.
