### ISSUE TITLE
[Feature] Adjust default Sentence List view properties

### ISSUE THREAD

**Issue by stappan** [MetaCell/sckan-composer#351]
User Story: When I log into Composer, I want to see the work I need to do & those records that I have previously worked on FIRST by default. I do not want to see sentences in this list that have been finished (those with status = completed; or excluded).

Acceptance criteria:
1. Sort sentences by owner = user (the person signed in)
2. Sort sentences by Last edited column (most recent = top)
3. Apply filters by default upon login to show only sentences with the following statuses: compose later; compose now; needs further review; open; ready to compose.

If user wants to see all sentences, they only need to clear filters. 

Priority: high.

**Comment by iliasziogas** [comment]
I agree with the acceptance criteria. @stappan

**Comment by stappan** [comment]
@ddelpiano can you please determine effort for this request? We'd like this added to the next sprint. thx

**Comment by stappan** [comment]
@ddelpiano can you please pop the effort you expect for this please? I'd like to review all proposed tasks by the amount of effort needed prior to adding them to sprints please.

**Comment by ddelpiano** [comment]
8 hrs, comprehensive of automated test implementation.

**Comment by stappan** [comment]
excellent; let's add this to today's sprint.

**Comment by stappan** [comment]
@iliasziogas I've tested this on staging, and think it looks great. please alert here if you run into any challenges: [https://composer.sckan.stage.metacell.us/](url)
