### ISSUE TITLE
add connected_from uri column to the export

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/sckan-composer#367]
acceptance criteria:
- add another column for connected_from called connected_from_uris which will list the URIs instead of the rdfs names of the entities.
- @stappan please include any other change of column names, order of the columns or other that you would like us to work on. Thx

**Comment by stappan** [comment]
@ddelpiano here's the new export template: [export template](https://docs.google.com/spreadsheets/d/1MFsSRQmHeQ9rhENN0aCJcBcPuHGO7FI0hebIkLTgp74/edit?usp=sharing)

Let me know if you have questions? In this export, only rows that have data should be exported. Items that are free text (alerts, statement preview) will have an Object text, but not an object URI since they are annotations.

**Comment by stappan** [comment]
Please use column labels as provided in Export template above, I filled in a mock-population to show the values that could be exported...i hope that makes sense.

**Comment by ddelpiano** [comment]
> @ddelpiano here's the new export template: [export template](https://docs.google.com/spreadsheets/d/1MFsSRQmHeQ9rhENN0aCJcBcPuHGO7FI0hebIkLTgp74/edit?usp=sharing)
> 
> Let me know if you have questions? In this export, only rows that have data should be exported. Items that are free text (alerts, statement preview) will have an Object text, but not an object URI since they are annotations.

Hi @stappan few notes:
- the ID in the first column is an information that is not available at the moment, this would require to modify the ingestion. It cannot fit this sprint since the original scope of this card was to change column names and shift the order, let me know if you want me to open a separate request for this.
- first row contains a predicate we've never seen (composerGenLabel), is this for a future request?
- Predicate URI is not an information we hold currently in the model, we only have the predicate, I can open a separate card to support the Predicate URI as part of the current mapping exists for the export, let me know.
- Direct Experimental Evidence, Expert Inference, Expert Knowledge, Indirect Experimental Evidence, Laterality Difference, Not relevant - Could you please tell us what these columns should give you? Again, we can open a separate ticket for this.

Thanks.

**Comment by stappan** [comment]
@ddelpiano @gidili how many hours will it take to actually get what i want here?

**Comment by stappan** [comment]
@ddelpiano the predicate, composerGenLabel, is to support the export of the statement preview. see #312 which was also in this sprint.

**Comment by stappan** [comment]
@ddelpiano for the first column , it's simply 
![image](https://github.com/user-attachments/assets/35e6ca8e-6997-41fd-b65d-8976f912f06f)
Do you need to store it? or just compute it?

**Comment by ddelpiano** [comment]
> @ddelpiano the predicate, composerGenLabel, is to support the export of the statement preview. see #312 which was also in this sprint.

#312 refers to a new column not a new row. Thanks

**Comment by ddelpiano** [comment]
> @ddelpiano Direct Experimental Evidence, Expert Inference, Expert Knowledge, Indirect Experimental Evidence, Laterality Difference, Not relevant - Could you please tell us what these columns should give you? Again, we can open a separate ticket for this. these are already exported by Composer. no changes needed, other than match the position I placed them in.

I would assume these are coming from the tags then, for the order at the moment it depends by the order these have been created. If what provided is the same of what was before there should be no changes required, otherwise we need to extend the mapping to the tags, I don't have clear estimate for this since I need to look into what can be done to manipulate the order of something that is dynamically created through the admin interface (and so the backend does not know about its existence).

**Comment by ddelpiano** [comment]
> @ddelpiano for the first column , it's simply ![image](https://private-user-images.githubusercontent.com/106172226/393878540-35e6ca8e-6997-41fd-b65d-8976f912f06f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTU4MjUsIm5iZiI6MTczMzc1NTUyNSwicGF0aCI6Ii8xMDYxNzIyMjYvMzkzODc4NTQwLTM1ZTZjYThlLTY5OTctNDFmZC1iNjVkLTg5NzZmOTEyZjA2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxNDQ1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDYwM2E3ZTE0NDZlMzhkYzkzM2NlNTA4MmQ3NTBlMDQ5OWM0MzE4ZjJiOTc2NWQzODg3Nzc2YjNjOWI1ZWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D4oSlZIS81JoghgikFrb3UoM5WQUpDTgoGuB-Q-78KM) Do you need to store it? or just compute it?

it needs to be stored from neurondm since it's not always consistent in the number of strings at the end of the URI that are making the id, e.g. http://uri.interlex.org/tgbugs/uris/readable/neuron-type-bolew-unbranched-2 it's only the last one where http://uri.interlex.org/tgbugs/uris/readable/femrep/60 are the last 2 strings of the uri.

**Comment by stappan** [comment]
> > @ddelpiano Direct Experimental Evidence, Expert Inference, Expert Knowledge, Indirect Experimental Evidence, Laterality Difference, Not relevant - Could you please tell us what these columns should give you? Again, we can open a separate ticket for this. these are already exported by Composer. no changes needed, other than match the position I placed them in.
> 
> I would assume these are coming from the tags then, for the order at the moment it depends by the order these have been created. If what provided is the same of what was before there should be no changes required, otherwise we need to extend the mapping to the tags, I don't have clear estimate for this since I need to look into what can be done to manipulate the order of something that is dynamically created through the admin interface (and so the backend does not know about its existence).

Ah, yes, those are tags that have the checkbox to be included in export. The order doesn't matter at this time. I've opened a ticket for the backlog about improving visibility in the admin interface: #375

**Comment by stappan** [comment]
> > @ddelpiano for the first column , it's simply ![image](https://private-user-images.githubusercontent.com/106172226/393878540-35e6ca8e-6997-41fd-b65d-8976f912f06f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTU4MjUsIm5iZiI6MTczMzc1NTUyNSwicGF0aCI6Ii8xMDYxNzIyMjYvMzkzODc4NTQwLTM1ZTZjYThlLTY5OTctNDFmZC1iNjVkLTg5NzZmOTEyZjA2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxNDQ1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDYwM2E3ZTE0NDZlMzhkYzkzM2NlNTA4MmQ3NTBlMDQ5OWM0MzE4ZjJiOTc2NWQzODg3Nzc2YjNjOWI1ZWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D4oSlZIS81JoghgikFrb3UoM5WQUpDTgoGuB-Q-78KM) Do you need to store it? or just compute it?
> 
> it needs to be stored from neurondm since it's not always consistent in the number of strings at the end of the URI that are making the id, e.g. http://uri.interlex.org/tgbugs/uris/readable/neuron-type-bolew-unbranched-2 it's only the last one where http://uri.interlex.org/tgbugs/uris/readable/femrep/60 are the last 2 strings of the uri.

Wouldn't this just be able to be done by parsing anything past /readable/ and any / after "readable/" is a dash?

**Comment by stappan** [comment]
> > @ddelpiano the predicate, composerGenLabel, is to support the export of the statement preview. see #312 which was also in this sprint.
> 
> #312 refers to a new column not a new row. Thanks

It's the statement preview (see column H). In the current export, there was a mismash of columns that would just continue to expand willy-nilly as the software expanded it's functionality. This organization of making a row for each triple ensures the number of columns is more stable from release to release. Does this make sense?

**Comment by stappan** [comment]
I created a new ticket for the predicate URIs here: #373

**Comment by ddelpiano** [comment]
> > > @ddelpiano for the first column , it's simply ![image](https://private-user-images.githubusercontent.com/106172226/393878540-35e6ca8e-6997-41fd-b65d-8976f912f06f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTU4MjUsIm5iZiI6MTczMzc1NTUyNSwicGF0aCI6Ii8xMDYxNzIyMjYvMzkzODc4NTQwLTM1ZTZjYThlLTY5OTctNDFmZC1iNjVkLTg5NzZmOTEyZjA2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxNDQ1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDYwM2E3ZTE0NDZlMzhkYzkzM2NlNTA4MmQ3NTBlMDQ5OWM0MzE4ZjJiOTc2NWQzODg3Nzc2YjNjOWI1ZWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D4oSlZIS81JoghgikFrb3UoM5WQUpDTgoGuB-Q-78KM) Do you need to store it? or just compute it?
> > 
> > 
> > it needs to be stored from neurondm since it's not always consistent in the number of strings at the end of the URI that are making the id, e.g. http://uri.interlex.org/tgbugs/uris/readable/neuron-type-bolew-unbranched-2 it's only the last one where http://uri.interlex.org/tgbugs/uris/readable/femrep/60 are the last 2 strings of the uri.
> 
> Wouldn't this just be able to be done by parsing anything past /readable/ and any / after "readable/" is a dash?

If you prefer yes but we cannot guarantee then on the integrity of the id since the translation from slash to dash could be changed or could use different rules in certain cases. If you are ok with that we can generate this from the url.

**Comment by stappan** [comment]
@ddelpiano yep you're totally right. thanks! - i discussed with @tgbugs - you should import the rdfs:label from neurondm for the neuron populations 
Should i create a new request - or should it be added to #373 ?
